name: iOS CI/CD with Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone 15" || true
          sleep 30

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Build and Test
        run: |
          xcodebuild clean test \
          -project TimeRanger.xcodeproj \
          -scheme TimeRanger \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
          CODE_SIGNING_ALLOWED=NO

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: fastlane pilot upload
