name: iOS CI/CD with Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Build and Test
        run: |
          xcodebuild clean test \
          -project TimeRanger.xcodeproj \
          -scheme TimeRanger \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
          CODE_SIGNING_ALLOWED=NO

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: fastlane pilot upload
